# Generated by Django 2.0.4 on 2018-05-21 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0002_device_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('module_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MainDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('device_code', models.TextField(max_length=6)),
                ('description', models.TextField()),
                ('last_sync', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('sensor_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(max_length=10)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='SlaveDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('description', models.TextField()),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.MainDevice')),
            ],
        ),
        migrations.CreateModel(
            name='SlaveDeviceAlg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('start_value', models.IntegerField()),
                ('stop_value', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.ControlledModule')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Sensor')),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.AlterField(
            model_name='token',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.MainDevice'),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.AddField(
            model_name='sensor',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.SlaveDevice'),
        ),
        migrations.AddField(
            model_name='controlledmodule',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.SlaveDevice'),
        ),
    ]
