# Generated by Django 2.0.5 on 2018-05-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20180521_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindevice',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='maindevice',
            name='last_sync',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='value',
            field=models.IntegerField(),
        ),
    ]
